### ISSUE TITLE
sonos.play gives no attribute error

### ISSUE THREAD

**Issue by koenvb** [pfischi/shSonos#83]
I was trying to use the plugin for smarthome.py.
Newest broker and plugin.

when I create a logic according the docs  I get following error.

```
2016-12-09  14:56:56 ERROR    sonos        Logic: sonos, File: /usr/smarthome/logics/sonos_muziek.py, Line: 6, Method: <module>, Exception: 'Sonos' object has no attribute 'sonos_keuken'
Traceback (most recent call last):
  File "/usr/smarthome/lib/scheduler.py", line 355, in _task
    exec(obj.bytecode)
  File "/usr/smarthome/logics/sonos_muziek.py", line 6, in <module>
    sh.sonos.sonos_keuken.play = True
AttributeError: 'Sonos' object has no attribute 'sonos_keuken'

```

My logic is very simple

```
#!/usr/bin/env python
#

logger.info("Sonos")
if sh.gelijkvloers.voute.licht_bureau_a_u:
	sh.sonos.sonos_keuken.play(1)
```

Could you help me to understand how to send a command to a speaker using a logic?
It works when I do sh.sonos.get_version() but no speaker commands are recognized.
Looking into the code I could not figure out how you send the command to the speaker?
Thanks a lot!

**Comment by pfischi** [comment]
Can you post your configured sonos item?

Koen <notifications@github.com> schrieb am Fr. 9. Dez. 2016 um 15:13:

**Comment by koenvb** [comment]
I added all the items into one smarthome.conf file under items.
The sonos part is added at the bottom of the file

```
	[sonos_keuken]
    sonos_uid = rincon_000e5831522a01400

    [[mute]]
        type = bool
        enforce_updates = True
        visu_acl = rw
        sonos_recv = mute
        sonos_send = mute

        [[[group_command]]]
            type = bool
            value = 0

    [[led]]
        type = bool
        enforce_updates = True
        visu_acl = rw
        sonos_recv = led
        sonos_send = led

        [[[group_command]]]
            type = bool
            value = 0

    [[volume]]
        type = num
        enforce_updates = True
        visu_acl = rw
        sonos_recv = volume
        sonos_send = volume

        [[[group_command]]]
            type = bool
            value = 0

    [[max_volume]]
        type = num
        enforce_updates = True
        visu_acl = rw
        sonos_recv = max_volume
        sonos_send = max_volume

        [[[group_command]]]
            type = bool
            value = 0

    [[stop]]
        type = bool
        enforce_updates = True
        visu_acl = rw
        sonos_recv = stop
        sonos_send = stop

    [[play]]
        type = bool
        enforce_updates = True
        visu_acl = rw
        sonos_recv = play
        sonos_send = play

    [[seek]]
        type = str
        enforce_updates = True
        visu_acl = rw
        sonos_send = seek    #use HH:mm:ss

    [[pause]]
        type = bool
        enforce_updates = True
        visu_acl = rw
        sonos_recv = pause
        sonos_send = pause

    [[next]]
        type = foo
        enforce_updates = True
        sonos_send = next
        visu_acl = rw

    [[previous]]
        type = foo
        enforce_updates = True
        sonos_send = previous
        visu_acl = rw

    [[track_title]]
        type = str
        sonos_recv = track_title

    [[track_album]]
        type = str
        sonos_recv = track_album

    [[track_duration]]
        type = str
        sonos_recv = track_duration
        visu_acl = rw

    [[track_position]]
        type = str
        sonos_recv = track_position
        visu_acl = rw

    [[track_artist]]
        type = str
        sonos_recv = track_artist

    [[track_uri]]
        type = str
        sonos_recv = track_uri
        visu_acl = rw

    [[track_album_art]]
        type = str
        sonos_recv = track_album_art

    [[playlist_position]]
        type = num
        sonos_recv = playlist_position
        visu_acl = rw

    [[playlist_total_tracks]]
        type = num
        sonos_recv = playlist_total_tracks

    [[streamtype]]
        type = str
        sonos_recv = streamtype
        visu_acl = rw

    [[play_uri]]
        type = str
        enforce_updates = True
        sonos_send = play_uri

    [[play_tunein]]
        # 'play_tunein' expects a radio station name
        # The name will be searched within TuneIn and the first match is played.
        # To make sure the correct radio station is played provide the full radio station 
        # showing in the Sonos app.
        type = str
        enforce_updates = True
        sonos_send = play_tunein

    [[play_snippet]]
        type = str
        enforce_updates = True
        sonos_send = play_snippet

        [[[volume]]]
            type = num
            value = -1

        [[[group_command]]]
            type = bool
            value = 0

    [[play_tts]]
        type = str
        enforce_updates = True
        sonos_send = play_tts
        visu_acl = rw

        [[[volume]]]
            type = num
            value = -1

        [[[language]]]
            type = str
            value = 'de'

        [[[group_command]]]
            type = bool
            value = 0

    [[radio_show]]
        type = str
        sonos_recv = radio_show
        visu_acl = rw

    [[radio_station]]
        type = str
        sonos_recv = radio_station
        visu_acl = rw

    [[uid]]
        type = str
        sonos_recv = uid
        visu_acl = rw

    [[ip]]
        type = str
        sonos_recv = ip
        visu_acl = rw

    [[model]]
        type = str
        sonos_recv = model
        visu_acl = rw

    [[model_number]]
        type = str
        sonos_recv = model_number
        visu_acl = rw

    [[display_version]]
        type = str
        sonos_recv = display_version
        visu_acl = rw

    [[household_id]]
        type = str
        sonos_recv = household_id
        visu_acl = rw

    [[zone_name]]
        type = str
        sonos_recv = zone_name
        visu_acl = rw

    [[zone_icon]]
        type = str
        sonos_recv = zone_icon
        visu_acl = rw

    [[serial_number]]
        type = str
        sonos_recv = serial_number
        visu_acl = rw

    [[software_version]]
        type = str
        sonos_recv = software_version
        visu_acl = rw

    [[hardware_version]]
        type = str
        sonos_recv = hardware_version
        visu_acl = rw

    [[mac_address]]
        type = str
        sonos_recv = mac_address
        visu_acl = rw

    [[status]]
        type = bool
        sonos_recv = status
        visu_acl = rw

    [[join]]
        type = str
        enforce_updates = True
        sonos_send = join
        visu_acl = rw

    [[unjoin]]
        type = foo
        enforce_updates = True
        sonos_send = unjoin
        visu_acl = rw

    [[partymode]]
        type = foo
        enforce_updates = True
        sonos_send = partymode
        visu_acl = rw

    [[volume_up]]
        type = foo
        enforce_updates = True
        visu_acl = rw
        sonos_send = volume_up

        [[[group_command]]]
            type = bool
            value = 0

    [[volume_down]]
        type = foo
        enforce_updates = True
        visu_acl = rw
        sonos_send = volume_down

        [[[group_command]]]
            type = bool
            value = 0

    [[additional_zone_members]]
        type = str
        visu_acl = rw
        sonos_recv = additional_zone_members

    [[bass]]
        type = num
        visu_acl = rw
        sonos_recv = bass
        sonos_send = bass

        [[[group_command]]]
            type = bool
            value = 0

    [[treble]]
        type = num
        visu_acl = rw
        sonos_recv = treble
        sonos_send = treble

        [[[group_command]]]
            type = bool
            value = 0

    [[loudness]]
        type = bool
        visu_acl = rw
        sonos_recv = loudness
        sonos_send = loudness

        [[[group_command]]]
            type = bool
            value = 0

    [[playmode]]
        type = str
        enforce_updates = True
        visu_acl = rw
        sonos_recv = playmode
        sonos_send = playmode

    [[alarms]]
        type = dict
        enforce_updates = True
        visu_acl = rw
        sonos_recv = alarms
        sonos_send = alarms

    [[is_coordinator]]
        type = bool
        sonos_recv = is_coordinator

    [[tts_local_mode]]
        type = bool
        sonos_recv = tts_local_mode

    [[sonos_playlists]]
        type = str  
        sonos_send = sonos_playlists
        enforce_updates = True

    [[load_sonos_playlist]]
        type = str
        sonos_send = load_sonos_playlist
        enforce_updates = True

        [[[play_after_insert]]]
            type = bool
            value = 1

        [[[clear_queue]]]
            type = bool
            value = 1

    [[balance]]
        type = num
        visu_acl = rw
        sonos_recv = balance
        sonos_send = balance

        [[[group_command]]]
            type = bool
            value = 0

    [[wifi_state]]
        type = bool
        visu_acl = rw
        sonos_recv = wifi_state
        sonos_send = wifi_state

        [[[persistent]]]
            type = bool
            value = 0

    [[clear_queue]]    
        type = bool
        enforce_updates = True
        sonos_send = clear_queue
```

**Comment by koenvb** [comment]
If I use the CLI plugin (telnet) and do 
`up sonos_keuken.play = True` 

Then the sonos start playing

**Comment by pfischi** [comment]
Try to call the function play() with:

sh.sonos_keuken.play(1)

This should do the trick.

**Comment by pfischi** [comment]
Working now?

**Comment by koenvb** [comment]
`
2016-12-09  16:03:47 ERROR    sonos        Logic: sonos, File: /usr/smarthome/logics/sonos_muziek.py, Line: 6, Method: <module>, Exception: 'bool' object is not callable
Traceback (most recent call last):
  File "/usr/smarthome/lib/scheduler.py", line 355, in _task
    exec(obj.bytecode)
  File "/usr/smarthome/logics/sonos_muziek.py", line 6, in <module>
    sh.sonos_keuken.play(1)
TypeError: 'bool' object is not callable

`

My logic

```
#!/usr/bin/env python
#

logger.info("Sonos")
if sh.gelijkvloers.voute.licht_bureau_a_u:
        sh.sonos_keuken.play(1)
        logger.info(sh.sonos.version())

```

**Comment by pfischi** [comment]
Ok, i'll take a look to this issue.

Koen <notifications@github.com> schrieb am Fr. 9. Dez. 2016 um 16:06:

**Comment by koenvb** [comment]
Hmmm I think this worked. Will keep you posted.

```
#!/usr/bin/env python
#

logger.info("Sonos")
if sh.gelijkvloers.voute.licht_bureau_a_u:
        sh.sonos_keuken.play
```
